# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88d98d5d57dde8f39be08760ab115cad9857b486344d266929da130e9e96eef56c54c4d3ba8d4380c4c133cf693846409cdbf48f4ee4393076af2834a4185ded

test:
  secret_key_base: 1e8b0ab0cbb1255f054d4a03901672c456395ba8d9fc21f32b4d9dd38f73b8d098fdf7e344fd01142677b12006c35168b7c2ee6f627ebf44e8a9fce4c4d5d707

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
